import os

QUALITY_MODEL_REPO_ID = os.getenv("QUALITY_MODEL_REPO_ID")
DURATION_MODEL_REPO_ID = os.getenv("DURATION_MODEL_REPO_ID")

QUALITY_MODEL_PATH = os.getenv("QUALITY_MODEL_PATH")
DURATION_MODEL_PATH = os.getenv("DURATION_MODEL_PATH")